name: Python application test

on:
  push:
    branches: [ main ]
    paths:
      - 'dags/**'
      - '.github/workflows/python-tests.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set AIRFLOW_HOME and additional Python paths
      run: |
        echo "AIRFLOW_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_WORKSPACE/dags:$GITHUB_WORKSPACE/utils:${PYTHONPATH}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Tests
      run: pytest

